const data = {
    products: [
      {
        _id: '1',
        name: 'TIN THE BEARD',
        category: 'ELITE',
        image: '/images/p1.jpg',
        price: 999,
        brand: '...',
        rating: 5,
        numReviews: 99,
        description: '...',
      },
      {
        _id: '2',
        name: 'PIPENEX degenerao',
        category: 'PATAS NEGRAS',
        image: '/images/p2.jpg',
        price: -100,
        brand: '...',
        rating: 0,
        numReviews: 0,
        description: '...',
      },
      {
        _id: '3',
        name: 'Platypunk',
        category: '¿?',
        image: '/images/p3.jpg',
        price: 69,
        brand: '...',
        rating: 4.5,
        numReviews: 17,
        description: '...',
      },
      {
        _id: '4',
        name: 'Sandy',
        category: 'Diosa del olimpo',
        image: '/images/p4.jpg',
        price: 999,
        brand: '...',
        rating: 5,
        numReviews: 99,
        description: '...',
      },
      {
        _id: '5',
        name: 'Landegod',
        category: 'Supremo',
        image: '/images/p5.jpg',
        price: 69,
        brand: '...',
        rating: 3,
        numReviews: 69,
        description: '...',
      },
      {
        _id: '6',
        name: 'Paula <3',
        category: 'poto',
        image: '/images/p6.jpg',
        price: 999,
        brand: '...',
        rating: 5,
        numReviews: 69,
        description: '...',
      },
    ],
  };
  export default data;