version: "3.7"
services:
    nodeapp:
        build:
            context: ./webapp/
            dockerfile: Dockerfile
        image: nodeapp
        depends_on:
            - db
        ports:
            - "3000:8080"
        volumes:
            - ./webapp:/usr/src/app
            - /usr/src/app/node_modules
    db:
        image: postgres:12.4
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d/
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4:4.27
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: postgres
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
volumes:
    db-data:
    pgadmin-data:
    webapp:

networks:
    default:
        external:
            name: web