export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const POPULAR_PRODUCT_DETAILS_REQUEST = 'POPULAR_PRODUCT_DETAILS_REQUEST';
export const POPULAR_PRODUCT_DETAILS_SUCCESS = 'POPULAR_PRODUCT_DETAILS_SUCCESS';
export const POPULAR_PRODUCT_DETAILS_FAIL = 'POPULAR_PRODUCT_DETAILS_FAIL';

export const COMENTARIO_PRODUCT_DETAILS_REQUEST = 'COMENTARIO_PRODUCT_DETAILS_REQUEST';
export const COMENTARIO_PRODUCT_DETAILS_SUCCESS = 'COMENTARIO_PRODUCT_DETAILS_SUCCESS';
export const COMENTARIO_PRODUCT_DETAILS_FAIL = 'COMENTARIO_PRODUCT_DETAILS_FAIL';

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const PROD_CATEGORY_LIST_REQUEST = 'PROD_CATEGORY_LIST_REQUEST';
export const PROD_CATEGORY_LIST_SUCCESS = 'PROD_CATEGORY_LIST_SUCCESS';
export const PROD_CATEGORY_LIST_FAIL = 'PROD_CATEGORY_LIST_FAIL';